name: Build and Upload

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number for the build"
        required: true
        type: string
      android_key_path:
        description: "The path to the Android key file, relative to app directory (e.g., neko.jks)"
        required: false
        default: "neko.jks"
        type: string
      android_key_alias:
        description: "The alias of the Android key"
        required: false
        default: "neko"
        type: string
      android_keystore_password:
        description: "The password for the Android keystore"
        required: false
        type: string
        default: "neko2233"
      android_key_password:
        description: "The password for the Android key"
        required: false
        type: string
        default: "neko2233"

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        # Optionally include specific configurations for Android if needed later
        # include:
        #   - platform: ubuntu-latest
        #     build_android: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # --- Start of Android Environment Setup (Linux Only) ---
      - name: Install Rust Android targets
        if: matrix.platform == 'ubuntu-latest'
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Setup Java (JDK)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/setup-java@v4
        with:
          distribution: "temurin" # Or another distribution like 'zulu'
          java-version: "17"      # Common requirement for modern Android dev

      - name: Setup Android SDK
        if: matrix.platform == 'ubuntu-latest'
        uses: android-actions/setup-android@v3
        # No specific sdk-version needed, it sets up the command-line tools

      - name: Install Android SDK Components (NDK, Platform Tools, Build Tools)
        if: matrix.platform == 'ubuntu-latest'
        # Use sdkmanager (provided by setup-android) to install required components
        # NDK 25.1.8937393 is often recommended for Tauri
        # Adjust android-34 and build-tools;34.0.0 if your project targets differently
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393" "platform-tools"

      - name: Set up Android signing environment variables
        if: matrix.platform == 'ubuntu-latest' && github.event.inputs.android_keystore_password != '' && github.event.inputs.android_key_password != ''
        run: |
          # Set environment variables used by Tauri's Android build process
          echo "ANDROID_KEYSTORE_PATH=${{ github.workspace }}/app/${{ github.event.inputs.android_key_path }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_ALIAS=${{ github.event.inputs.android_key_alias }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_PASSPHRASE=${{ github.event.inputs.android_keystore_password }}" >> $GITHUB_ENV # Note: Tauri uses PASSPHRASE
          echo "ANDROID_KEY_ALIAS=${{ github.event.inputs.android_key_alias }}" >> $GITHUB_ENV # Redundant but sometimes useful
          echo "ANDROID_KEY_PASSPHRASE=${{ github.event.inputs.android_key_password }}" >> $GITHUB_ENV # Note: Tauri uses PASSPHRASE
        # Added condition to only set these if passwords are provided, preventing errors if not signing

      # --- End of Android Environment Setup ---

      - name: Install Linux dependencies (for Desktop build)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev

      # --- Desktop Build ---
      - name: Build Tauri app (Desktop)
        # Run desktop build for all platforms
        run: cd app && pnpm build && pnpm vite build && pnpm tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          # ANDROID_HOME and NDK_HOME are usually set automatically by setup-android/setup-java
          # ANDROID_HOME: ${{ env.ANDROID_HOME }} # Typically not needed to set explicitly here
          # NDK_HOME: ${{ env.ANDROID_NDK_LATEST_HOME }} # Typically not needed to set explicitly here

      # --- Desktop Artifact Uploads ---
      - name: Upload Ubuntu artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-${{ github.event.inputs.version }}
          path: |
            app/src-tauri/target/release/bundle/**/*.deb
            app/src-tauri/target/release/bundle/**/*.AppImage
            app/src-tauri/target/release/bundle/**/*.rpm

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/dmg/*.dmg

      # --- Android Build (Linux Only) ---
      - name: Build Tauri app for Android
        if: matrix.platform == 'ubuntu-latest'
        run: cd app && pnpm tauri android build
        env:
          # Reuse desktop signing secrets if needed, or use separate Android secrets
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          # ANDROID_* variables for signing are already set in the environment via $GITHUB_ENV step

      # --- Android Artifact Upload ---
      - name: Upload Android artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: android-build-${{ github.event.inputs.version }}
          # Adjust path based on whether you build APK or AAB (check tauri.conf.json)
          # Default APK path:
          path: app/src-tauri/gen/android/app/build/outputs/apk/**/release/*.apk
          # Example AAB path:
          # path: app/src-tauri/gen/android/app/build/outputs/bundle/release/*.aab
