name: Build and Upload

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number for the build"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Update app version in tauri.conf.json
        run: |
          if [[ "${{ matrix.platform }}" == "ubuntu-latest" ]]; then
            sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"${{ github.event.inputs.version }}\"/" app/src-tauri/tauri.conf.json
          elif [[ "${{ matrix.platform }}" == "macos-latest" ]]; then
            sed -i '' "s/\"version\": \"[^\"]*\"/\"version\": \"${{ github.event.inputs.version }}\"/" app/src-tauri/tauri.conf.json
          elif [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            (Get-Content -Path "app/src-tauri/tauri.conf.json" -Raw) -replace '"version": "[^"]*"', '"version": "${{ github.event.inputs.version }}"' | Set-Content -Path "app/src-tauri/tauri.conf.json"
          fi

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev

      - name: Build Tauri app
        run: cd app && pnpm tauri build

      - name: Upload Ubuntu artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/**/*.{deb,AppImage}

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/dmg/*.dmg
