name: Build and Upload

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version number for the build"
        required: true
        type: string
      android_key_path:
        description: "The path to the Android key file, relative to app directory"
        required: false
        default: "neko.jks"
        type: string
      android_key_alias:
        description: "The alias of the Android key"
        required: false
        default: "neko"
        type: string
      android_keystore_password:
        description: "The password for the Android keystore"
        required: false
        type: string
        default: "neko2233"
      android_key_password:
        description: "The password for the Android key"
        required: false
        type: string
        default: "neko2233"

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # 新增步骤：安装 Rust Android 目标
      - name: Install Rust Android targets
        if: matrix.platform == 'ubuntu-latest'
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi
      - name: Setup Java
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        if: matrix.platform == 'ubuntu-latest'
        uses: android-actions/setup-android@v3

      - name: Install Android components
        if: matrix.platform == 'ubuntu-latest'
        run: |
          echo "y" | sdkmanager "platforms;android-34" "build-tools;34.0.0" "ndk;25.1.8937393"

      - name: Set up Android signing secrets
        if: matrix.platform == 'ubuntu-latest'
        run: |
          echo "ANDROID_KEYSTORE_PATH=${{ github.event.inputs.android_key_path }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_ALIAS=${{ github.event.inputs.android_key_alias }}" >> $GITHUB_ENV
          echo "ANDROID_KEYSTORE_PASSWORD=${{ github.event.inputs.android_keystore_password }}" >> $GITHUB_ENV
          echo "ANDROID_KEY_PASSWORD=${{ github.event.inputs.android_key_password }}" >> $GITHUB_ENV

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev

      - name: Build Tauri app
        run: cd app && pnpm build && pnpm vite build && pnpm tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload Ubuntu artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-${{ github.event.inputs.version }}
          path: |
            app/src-tauri/target/release/bundle/**/*.deb
            app/src-tauri/target/release/bundle/**/*.AppImage
            app/src-tauri/target/release/bundle/**/*.rpm

      - name: Upload Windows artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/nsis/*.exe

      - name: Upload macOS artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.event.inputs.version }}
          path: app/src-tauri/target/release/bundle/dmg/*.dmg

      - name: Add Android targets
        if: matrix.platform == 'ubuntu-latest'
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi
          rustup target add i686-linux-android
          rustup target add x86_64-linux-android

      - name: Build Tauri app for Android
        if: matrix.platform == 'ubuntu-latest'
        run: cd app && pnpm tauri build --target android
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload Android artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: android-build-${{ github.event.inputs.version }}
          path: app/src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk # Or aab/*.aab depending on the output

